using SVL.Avalonia.Models;
using System.Collections.ObjectModel;

namespace SVL.Avalonia.Services;

public sealed class LocalizationService
{
    private readonly AppUserSettingsStore _settingsStore;

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Catalog =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["zh-CN"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Window.Title"] = "Stardew Valley Launcher",
                ["Nav.Launch"] = "启动",
                ["Nav.Download"] = "下载",
                ["Nav.Tasks"] = "任务",
                ["Nav.Settings"] = "设置",
                ["Sidebar.CurrentPage"] = "当前页面",
                ["Sidebar.MigrationStatus"] = "迁移状态",
                ["Sidebar.MigrationPoint1"] = "- 保留全部导航结构",
                ["Sidebar.MigrationPoint2"] = "- 保留全部功能域（启动/下载/任务/设置）",
                ["Sidebar.MigrationPoint3"] = "- 正在逐页迁移原 WPF 视图",
                ["Sidebar.PathDetect"] = "路径探测",
                ["Launch.InstanceInfo"] = "实例信息",
                ["Launch.Mode"] = "启动模式",
                ["Launch.SafeLaunch"] = "安全启动",
                ["Launch.Status"] = "状态",
                ["Launch.Refresh"] = "刷新本机探测",
                ["Launch.VersionSelect"] = "版本选择",
                ["Launch.ModManage"] = "Mod管理",
                ["Launch.VersionSettings"] = "版本设置",
                ["Launch.Welcome"] = "欢迎使用星露谷物语启动器",
                ["Launch.GetStarted"] = "开始使用",
                ["Launch.Brand"] = "Stardew Valley Launcher",
                ["Launch.Status.Initializing"] = "等待初始化",
                ["Launch.Status.ReadingInstance"] = "正在读取实例状态",
                ["Launch.Status.StartingTitle"] = "正在启动游戏",
                ["Launch.Status.StartingSubtitle"] = "正在调用本地启动流程，请稍候...",
                ["Launch.Status.NoInstanceTitle"] = "尚未配置游戏实例",
                ["Launch.Status.NoInstanceSubtitle"] = "请先点击左侧版本选择进入实例管理，再返回启动页。",
                ["Launch.Status.ReadySmapiTitle"] = "实例已就绪（SMAPI）",
                ["Launch.Status.ReadyVanillaTitle"] = "实例已就绪（原版）",
                ["Launch.Status.ReadySubtitle"] = "可直接启动，或先进入版本设置调整参数。",
                ["Launch.Button.Launch"] = "启动游戏",
                ["Launch.Button.Launching"] = "启动中...",
                ["Launch.ModeValue.Auto"] = "自动",
                ["Launch.ModeValue.Smapi"] = "SMAPI",
                ["Launch.ModeValue.Vanilla"] = "原版",
                ["Launch.SafeLaunch.Enabled"] = "已开启",
                ["Launch.SafeLaunch.Disabled"] = "已关闭",
                ["Launch.Instance.NoneName"] = "暂无实例",
                ["Launch.Instance.NoneVersion"] = "请先添加游戏实例",
                ["Launch.Instance.NoneStatus"] = "未找到版本",
                ["Launch.Instance.SelectedLoaded"] = "已加载已选择实例",
                ["Launch.Instance.DetectedLocal"] = "已检测到本机游戏目录",
                ["Launch.Version.Modded"] = "模组版（SMAPI）",
                ["Launch.Version.Vanilla"] = "原版",
                ["Launch.Action.Refreshed"] = "已刷新本机探测结果（{0}）",
                ["Launch.Action.LoadedInstance"] = "已加载实例: {0}",
                ["Launch.Action.NoPathDetected"] = "未探测到本机游戏目录",
                ["Launch.Action.DetectedPath"] = "已探测到目录: {0}",
                ["Launch.Action.RequireInstance"] = "请先创建或选择实例",
                ["Launch.Action.InvalidInstancePath"] = "当前实例目录不可用，请先刷新路径",
                ["Launch.Action.TargetNotFound"] = "未找到可启动文件（模式: {0}）",
                ["Launch.Action.Started"] = "{0} 已启动: {1}，模式: {2}{3}{4}",
                ["Launch.Action.SafeTag"] = "（安全启动）",
                ["Launch.Action.ArgsTag"] = "，参数: {0}",
                ["Launch.Action.LaunchFailed"] = "启动失败，请检查文件权限或执行权限",
                ["Launch.Action.NavigateVersionSelect"] = "进入版本选择",
                ["Launch.Action.RequireValidInstance"] = "请先选择有效实例",
                ["Launch.Action.OpenModManage"] = "正在打开 Mod 管理",
                ["Launch.Action.OpenVersionSettings"] = "正在打开版本设置",
                ["Launch.Guide.NoInstanceLead"] = "请先添加游戏实例才能开始使用启动器：",
                ["Launch.Guide.Step1"] = "1. 点击左侧版本选择进入实例管理页面",
                ["Launch.Guide.Step2"] = "2. 使用添加功能选择游戏安装目录",
                ["Launch.Guide.Step3"] = "3. 支持多实例管理，方便切换不同版本",
                ["Launch.Guide.Step4"] = "4. 支持自动探测 Steam 和 GOG 版本",
                ["Launch.Guide.UsageTitle"] = "使用提示",
                ["Launch.Guide.UsageLine1"] = "点击左侧启动游戏按钮即可开始游玩 Stardew Valley。",
                ["Launch.Guide.UsageLine2"] = "使用版本选择可切换不同游戏版本；版本设置可配置启动参数和 Mod 选项。",
                ["Launch.Guide.UsageModManage"] = "左下角「Mod管理」按钮可直接跳转到该版本的 Mod 管理页面。",
                ["Settings.Title"] = "设置",
                ["Settings.Tab.Basic"] = "基本设置",
                ["Settings.Tab.Download"] = "下载设置",
                ["Settings.Tab.Personalization"] = "个性化",
                ["Settings.Tab.Other"] = "其他",
                ["Settings.Tab.About"] = "关于",
                ["Settings.Other.Subtitle"] = "运行时行为与调试选项",
                ["Settings.Other.ShowNotifications"] = "显示通知",
                ["Settings.Other.DebugMode"] = "启用调试模式",
                ["Settings.Other.LogLevel"] = "日志级别",
                ["Settings.Other.MinimizeOnStartup"] = "启动时最小化到托盘",
                ["Settings.Other.MinimizeOnClose"] = "关闭窗口时最小化到托盘",
                ["Settings.UiLanguage"] = "界面语言",
                ["Settings.ThemeMode"] = "主题模式",
                ["Settings.Save"] = "保存设置",
                ["Settings.OperationPath"] = "操作路径：基本设置 -> 下载设置 -> 个性化 -> 其他 -> 关于",
                ["Settings.Card.Update"] = "更新设置",
                ["Settings.Update.AutoCheck"] = "启动时自动检查更新",
                ["Settings.Update.Channel"] = "更新通道",
                ["Settings.Update.SourcePreference"] = "更新源偏好",
                ["Settings.Update.CheckNow"] = "立即检查更新",
                ["Settings.Update.StatusLabel"] = "更新状态",
                ["Settings.Update.LatestLabel"] = "最新版本",
                ["Settings.Update.SourceLabel"] = "更新源",
                ["Settings.Update.Checking"] = "正在检查更新...",
                ["Settings.Update.UpToDate"] = "已是最新版本",
                ["Settings.Update.Found"] = "发现新版本 {0}",
                ["Settings.Update.Skipped"] = "已忽略版本 {0}",
                ["Settings.Update.Failed"] = "检查更新失败",
                ["Settings.Update.OpenReleaseSuccess"] = "已打开发布页",
                ["Settings.Update.OpenReleaseFailed"] = "打开发布页失败，请稍后重试",
                    ["Settings.Basic.AutoConnect"] = "启动时自动连接服务器",
                    ["Settings.Basic.ServerAddress"] = "服务器地址",
                    ["Settings.Basic.SteamInviteCode"] = "Steam 邀请码",
                ["Settings.Card.NxmProtocol"] = "NXM 协议",
                ["Settings.Nxm.Status"] = "状态",
                ["Settings.Nxm.AutoRegister"] = "启动时尝试注册 NXM 协议",
                ["Settings.Nxm.Description"] = "用于浏览器中的 nxm:// 链接快速回传到启动器下载页。",
                ["Settings.Nxm.RegisterNow"] = "重新注册 NXM 协议",
                ["Download.CategoryTitle"] = "下载类别",
                ["Download.Category.Smapi"] = "SMAPI",
                ["Download.Category.SmapiSub"] = "模组启动器",
                ["Download.Category.Mods"] = "Mod",
                ["Download.Category.ModsSub"] = "单个模组",
                ["Download.Category.Modpacks"] = "Modpack",
                ["Download.Category.ModpacksSub"] = "整合包",
                ["Download.ActiveTasks"] = "进行中的任务",
                ["Download.NoActiveTasks"] = "当前无进行中任务",
                ["Download.HistoryTasks"] = "历史任务",
                ["Download.NoHistoryTasks"] = "当前无历史任务",
                ["Download.Task.Cancel"] = "取消",
                ["Download.Task.Retry"] = "重试",
                ["Download.Task.OpenReport"] = "打开报告",
                ["Download.Task.OpenBackup"] = "打开备份",
                ["Download.Task.CopyFailed"] = "复制失败明细",
                ["Download.Task.OpenRetryReport"] = "打开重试报告",
                ["Download.StatusPrefix"] = "状态: ",
                ["Download.Nxm.Title"] = "NXM 链接导入",
                ["Download.Nxm.Watermark"] = "粘贴 nxm://stardewvalley/mods/.../files/...",
                ["Download.Nxm.Import"] = "导入 NXM",
                ["Download.Url.Title"] = "URL 直链下载（真实网络）",
                ["Download.Url.Watermark"] = "https://example.com/file.zip",
                ["Download.Url.FileNameWatermark"] = "可选：自定义文件名（不填则自动推断）",
                ["Download.Url.Queue"] = "加入真实下载队列",
                ["Download.Path.WarningTitle"] = "未设置游戏安装目录",
                ["Download.Path.WarningDescription"] = "当前需要先配置实例中的游戏目录，下载与安装流程会使用该目录。",
                ["Download.Path.HintPrefix"] = "探测结果: ",
                ["Download.Path.GoInstance"] = "前往实例管理",
                ["Download.Search.SmapiTitle"] = "搜索 SMAPI",
                ["Download.Search.SmapiWatermark"] = "输入关键词",
                ["Download.Search.Button"] = "搜索",
                ["Download.Search.SelectFirst"] = "选择首条结果",
                ["Download.Search.ModTitle"] = "搜索 Mod",
                ["Download.Search.ModWatermark"] = "输入 Mod 关键词",
                ["Download.Search.OpenMod"] = "进入 Mod 搜索页",
                ["Download.Modpack.Title"] = "Modpack 导入",
                ["Download.Modpack.Description"] = "可通过搜索页选择整合包，或直接输入 URL 进入真实下载队列。",
                ["Download.Modpack.UrlWatermark"] = "https://example.com/modpack.zip",
                ["Download.Modpack.FileNameWatermark"] = "可选：自定义文件名（不填则自动推断）",
                ["Download.Modpack.Import"] = "导入 Modpack URL",
                ["Download.Modpack.OpenSearch"] = "进入 Modpack 搜索页"
            },
            ["en-US"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Window.Title"] = "Stardew Valley Launcher",
                ["Nav.Launch"] = "Launch",
                ["Nav.Download"] = "Download",
                ["Nav.Tasks"] = "Tasks",
                ["Nav.Settings"] = "Settings",
                ["Sidebar.CurrentPage"] = "Current Page",
                ["Sidebar.MigrationStatus"] = "Migration Status",
                ["Sidebar.MigrationPoint1"] = "- Keep all navigation structure",
                ["Sidebar.MigrationPoint2"] = "- Keep all feature domains (Launch/Download/Tasks/Settings)",
                ["Sidebar.MigrationPoint3"] = "- Migrating original WPF pages incrementally",
                ["Sidebar.PathDetect"] = "Path Detection",
                ["Launch.InstanceInfo"] = "Instance Info",
                ["Launch.Mode"] = "Launch Mode",
                ["Launch.SafeLaunch"] = "Safe Launch",
                ["Launch.Status"] = "Status",
                ["Launch.Refresh"] = "Refresh Detection",
                ["Launch.VersionSelect"] = "Version Select",
                ["Launch.ModManage"] = "Mods",
                ["Launch.VersionSettings"] = "Version Settings",
                ["Launch.Welcome"] = "Welcome to Stardew Valley Launcher",
                ["Launch.GetStarted"] = "Get Started",
                ["Launch.Brand"] = "Stardew Valley Launcher",
                ["Launch.Status.Initializing"] = "Initializing",
                ["Launch.Status.ReadingInstance"] = "Reading instance state",
                ["Launch.Status.StartingTitle"] = "Launching Game",
                ["Launch.Status.StartingSubtitle"] = "Starting local launch flow, please wait...",
                ["Launch.Status.NoInstanceTitle"] = "No Game Instance Configured",
                ["Launch.Status.NoInstanceSubtitle"] = "Open Version Select on the left to configure an instance first.",
                ["Launch.Status.ReadySmapiTitle"] = "Instance Ready (SMAPI)",
                ["Launch.Status.ReadyVanillaTitle"] = "Instance Ready (Vanilla)",
                ["Launch.Status.ReadySubtitle"] = "You can launch now or open Version Settings first.",
                ["Launch.Button.Launch"] = "Launch Game",
                ["Launch.Button.Launching"] = "Launching...",
                ["Launch.ModeValue.Auto"] = "Auto",
                ["Launch.ModeValue.Smapi"] = "SMAPI",
                ["Launch.ModeValue.Vanilla"] = "Vanilla",
                ["Launch.SafeLaunch.Enabled"] = "Enabled",
                ["Launch.SafeLaunch.Disabled"] = "Disabled",
                ["Launch.Instance.NoneName"] = "No Instance",
                ["Launch.Instance.NoneVersion"] = "Add a game instance first",
                ["Launch.Instance.NoneStatus"] = "Version Not Found",
                ["Launch.Instance.SelectedLoaded"] = "Loaded selected instance",
                ["Launch.Instance.DetectedLocal"] = "Detected local game directory",
                ["Launch.Version.Modded"] = "Modded (SMAPI)",
                ["Launch.Version.Vanilla"] = "Vanilla",
                ["Launch.Action.Refreshed"] = "Local detection refreshed ({0})",
                ["Launch.Action.LoadedInstance"] = "Loaded instance: {0}",
                ["Launch.Action.NoPathDetected"] = "No local game directory detected",
                ["Launch.Action.DetectedPath"] = "Detected directory: {0}",
                ["Launch.Action.RequireInstance"] = "Create or select an instance first",
                ["Launch.Action.InvalidInstancePath"] = "Current instance path is unavailable, refresh and retry",
                ["Launch.Action.TargetNotFound"] = "No launch target found (mode: {0})",
                ["Launch.Action.Started"] = "{0} Started: {1}, mode: {2}{3}{4}",
                ["Launch.Action.SafeTag"] = " (Safe Launch)",
                ["Launch.Action.ArgsTag"] = ", args: {0}",
                ["Launch.Action.LaunchFailed"] = "Launch failed, check permissions or executable access",
                ["Launch.Action.NavigateVersionSelect"] = "Open Version Select",
                ["Launch.Action.RequireValidInstance"] = "Select a valid instance first",
                ["Launch.Action.OpenModManage"] = "Opening Mod Management",
                ["Launch.Action.OpenVersionSettings"] = "Opening Version Settings",
                ["Launch.Guide.NoInstanceLead"] = "Please add a game instance before using the launcher:",
                ["Launch.Guide.Step1"] = "1. Click Version Select on the left",
                ["Launch.Guide.Step2"] = "2. Add your game install directory",
                ["Launch.Guide.Step3"] = "3. Multi-instance management is supported",
                ["Launch.Guide.Step4"] = "4. Steam and GOG auto-detection is supported",
                ["Launch.Guide.UsageTitle"] = "Usage Tips",
                ["Launch.Guide.UsageLine1"] = "Click Launch Game on the left to start playing Stardew Valley.",
                ["Launch.Guide.UsageLine2"] = "Use Version Select to switch instances and Version Settings to configure launch options.",
                ["Launch.Guide.UsageModManage"] = "The Mod Manage button at the lower-left jumps directly to this instance's mod management page.",
                ["Settings.Title"] = "Settings",
                ["Settings.Tab.Basic"] = "Basic",
                ["Settings.Tab.Download"] = "Download",
                ["Settings.Tab.Personalization"] = "Personalization",
                ["Settings.Tab.Other"] = "Other",
                ["Settings.Tab.About"] = "About",
                ["Settings.Other.Subtitle"] = "Runtime behavior and debug options",
                ["Settings.Other.ShowNotifications"] = "Show notifications",
                ["Settings.Other.DebugMode"] = "Enable debug mode",
                ["Settings.Other.LogLevel"] = "Log level",
                ["Settings.Other.MinimizeOnStartup"] = "Minimize to tray on startup",
                ["Settings.Other.MinimizeOnClose"] = "Minimize to tray on close",
                ["Settings.UiLanguage"] = "UI Language",
                ["Settings.ThemeMode"] = "Theme",
                ["Settings.Save"] = "Save Settings",
                ["Settings.OperationPath"] = "Flow: Basic -> Download -> Personalization -> Other -> About",
                ["Settings.Card.Update"] = "Update Settings",
                ["Settings.Update.AutoCheck"] = "Check for updates on startup",
                ["Settings.Update.Channel"] = "Update Channel",
                ["Settings.Update.SourcePreference"] = "Preferred Source",
                ["Settings.Update.CheckNow"] = "Check Now",
                ["Settings.Update.StatusLabel"] = "Status",
                ["Settings.Update.LatestLabel"] = "Latest",
                ["Settings.Update.SourceLabel"] = "Source",
                ["Settings.Update.Checking"] = "Checking for updates...",
                ["Settings.Update.UpToDate"] = "You are up to date",
                ["Settings.Update.Found"] = "New version found: {0}",
                ["Settings.Update.Skipped"] = "Skipped version {0}",
                ["Settings.Update.Failed"] = "Update check failed",
                ["Settings.Update.OpenReleaseSuccess"] = "Release page opened",
                ["Settings.Update.OpenReleaseFailed"] = "Failed to open release page",
                    ["Settings.Basic.AutoConnect"] = "Auto-connect to server on launch",
                    ["Settings.Basic.ServerAddress"] = "Server Address",
                    ["Settings.Basic.SteamInviteCode"] = "Steam Invite Code",
                ["Settings.Card.NxmProtocol"] = "NXM Protocol",
                ["Settings.Nxm.Status"] = "Status",
                ["Settings.Nxm.AutoRegister"] = "Try to register NXM protocol on startup",
                ["Settings.Nxm.Description"] = "Allows nxm:// links from browser to return to launcher download flow.",
                ["Settings.Nxm.RegisterNow"] = "Register NXM Protocol",
                ["Download.CategoryTitle"] = "Categories",
                ["Download.Category.Smapi"] = "SMAPI",
                ["Download.Category.SmapiSub"] = "Mod Loader",
                ["Download.Category.Mods"] = "Mods",
                ["Download.Category.ModsSub"] = "Single Mod",
                ["Download.Category.Modpacks"] = "Modpacks",
                ["Download.Category.ModpacksSub"] = "Collections",
                ["Download.ActiveTasks"] = "Active Tasks",
                ["Download.NoActiveTasks"] = "No active tasks",
                ["Download.HistoryTasks"] = "Task History",
                ["Download.NoHistoryTasks"] = "No history tasks",
                ["Download.Task.Cancel"] = "Cancel",
                ["Download.Task.Retry"] = "Retry",
                ["Download.Task.OpenReport"] = "Open Report",
                ["Download.Task.OpenBackup"] = "Open Backup",
                ["Download.Task.CopyFailed"] = "Copy Failure Details",
                ["Download.Task.OpenRetryReport"] = "Open Retry Report",
                ["Download.StatusPrefix"] = "Status: ",
                ["Download.Nxm.Title"] = "NXM Link Import",
                ["Download.Nxm.Watermark"] = "Paste nxm://stardewvalley/mods/.../files/...",
                ["Download.Nxm.Import"] = "Import NXM",
                ["Download.Url.Title"] = "Direct URL Download (Live)",
                ["Download.Url.Watermark"] = "https://example.com/file.zip",
                ["Download.Url.FileNameWatermark"] = "Optional: custom filename (auto if empty)",
                ["Download.Url.Queue"] = "Queue Real Download",
                ["Download.Path.WarningTitle"] = "Game Install Path Not Set",
                ["Download.Path.WarningDescription"] = "Set the game directory in Instances first; download and install flows depend on it.",
                ["Download.Path.HintPrefix"] = "Detection: ",
                ["Download.Path.GoInstance"] = "Go to Instances",
                ["Download.Search.SmapiTitle"] = "Search SMAPI",
                ["Download.Search.SmapiWatermark"] = "Enter keyword",
                ["Download.Search.Button"] = "Search",
                ["Download.Search.SelectFirst"] = "Select First Result",
                ["Download.Search.ModTitle"] = "Search Mods",
                ["Download.Search.ModWatermark"] = "Enter mod keyword",
                ["Download.Search.OpenMod"] = "Open Mod Search",
                ["Download.Modpack.Title"] = "Modpack Import",
                ["Download.Modpack.Description"] = "Pick a collection from search, or import by URL into the real download queue.",
                ["Download.Modpack.UrlWatermark"] = "https://example.com/modpack.zip",
                ["Download.Modpack.FileNameWatermark"] = "Optional: custom filename (auto if empty)",
                ["Download.Modpack.Import"] = "Import Modpack URL",
                ["Download.Modpack.OpenSearch"] = "Open Modpack Search"
            }
        };

    public event Action? LanguageChanged;

    public ObservableCollection<string> SupportedLanguages { get; } = ["zh-CN", "en-US"];

    public string CurrentLanguage { get; private set; } = "zh-CN";

    public LocalizationService(AppUserSettingsStore settingsStore)
    {
        _settingsStore = settingsStore;

        var settings = _settingsStore.Load();
        var language = string.IsNullOrWhiteSpace(settings.UiLanguage) ? "zh-CN" : settings.UiLanguage;
        CurrentLanguage = Catalog.ContainsKey(language) ? language : "zh-CN";
    }

    public string Get(string key)
    {
        if (Catalog.TryGetValue(CurrentLanguage, out var languageMap) &&
            languageMap.TryGetValue(key, out var localizedValue))
        {
            return localizedValue;
        }

        if (Catalog.TryGetValue("zh-CN", out var fallbackMap) &&
            fallbackMap.TryGetValue(key, out var fallbackValue))
        {
            return fallbackValue;
        }

        return key;
    }

    public void SetLanguage(string language)
    {
        if (string.IsNullOrWhiteSpace(language) || !Catalog.ContainsKey(language) ||
            string.Equals(CurrentLanguage, language, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        CurrentLanguage = language;

        var settings = _settingsStore.Load();
        settings.UiLanguage = language;
        _settingsStore.Save(settings);

        LanguageChanged?.Invoke();
    }
}
